SELECT TOP (5000)
    P.ANO_MES                       AS DIA_INT,
    P.INDICADOR,
    P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
    P.CONTRATO,
    P.NSU_TRX,
    P.CPF_CLIENTE,
    P.VLR_CONTRATO
FROM DEF..TB_CONSIG_AVERBADO_EXP P
WHERE P.CHAVE_LOJA = ?
  AND P.ANO_MES BETWEEN ? AND ?
  /*PRODUTO*/
  /*SITUACAO*/
ORDER BY P.ANO_MES DESC, P.VLR_CONTRATO DESC;
