WITH ATIVAS AS (
    SELECT DISTINCT CHAVE_LOJA
    FROM DATAWAREHOUSE..TB_INDICADORES_BE
    WHERE PERIODO BETWEEN ? AND ?
      AND QTD_ATIVOS > 0
),
PROD AS (
    SELECT
        P.CHAVE_LOJA,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO' THEN 1 ELSE 0 END) AS QTD_AVERBADO,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO' THEN P.VLR_CONTRATO ELSE 0 END) AS VLR_AVERBADO,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AGUARDANDO AVERBACAO' THEN 1 ELSE 0 END) AS QTD_AGUARDANDO,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AGUARDANDO AVERBACAO' THEN P.VLR_CONTRATO ELSE 0 END) AS VLR_AGUARDANDO,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'NAO AVERBADO' THEN 1 ELSE 0 END) AS QTD_NAO_AVERBADO,
        SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'NAO AVERBADO' THEN P.VLR_CONTRATO ELSE 0 END) AS VLR_NAO_AVERBADO
    FROM DEF..TB_CONSIG_AVERBADO_EXP P
    WHERE P.DATA_TRX >= CAST(? AS DATE)
      AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
      /*PRODUTO_P*/
      /*SITUACAO*/
    GROUP BY P.CHAVE_LOJA
),
TENT AS (
    SELECT
        T.CHAVE_LOJA,
        ISNULL(SUM(T.QTD_CLIENTES), 0) AS QTD_TENTATIVAS,
        SUM(T.QTD_CONVERTIDAS)      AS QTD_CONVERTIDAS
    FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
    WHERE T.DATA_ETAPA >= CAST(? AS DATE) AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
      /*PRODUTO_T*/
    GROUP BY T.CHAVE_LOJA
),
UNIVERSO AS (
    -- Primeiro as chaves com movimento no recorte; so depois o cadastro.
    -- UNION impede multiplicar a loja que produziu e tambem tentou.
    SELECT CHAVE_LOJA
    FROM PROD
    WHERE QTD_AVERBADO + QTD_AGUARDANDO + QTD_NAO_AVERBADO > 0
    UNION
    SELECT CHAVE_LOJA
    FROM TENT
    WHERE QTD_TENTATIVAS > 0
    /*INCLUIR_ATIVAS*/
),
LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        LTRIM(RTRIM(A.NOME_LOJA)) AS NOME_LOJA,
        A.MUNICIPIO,
        A.UF,
        H.DESC_GERENCIA_AREA,
        H.DESC_COORDENACAO,
        H.DESC_SUPERVISAO,
        CASE WHEN AT.CHAVE_LOJA IS NOT NULL THEN 1 ELSE 0 END AS ATIVA
    FROM UNIVERSO U
    INNER JOIN DATALAKE..DL_BRADESCO_EXPRESSO A ON A.CHAVE_LOJA = U.CHAVE_LOJA
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    LEFT JOIN ATIVAS AT ON AT.CHAVE_LOJA = A.CHAVE_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    L.CHAVE_LOJA,
    L.NOME_LOJA,
    L.MUNICIPIO,
    L.UF,
    L.DESC_GERENCIA_AREA,
    L.DESC_COORDENACAO,
    L.DESC_SUPERVISAO,
    L.ATIVA,
    ISNULL(P.QTD_AVERBADO, 0)     AS QTD_AVERBADO,
    ISNULL(P.VLR_AVERBADO, 0)     AS VLR_AVERBADO,
    ISNULL(P.QTD_AGUARDANDO, 0)   AS QTD_AGUARDANDO,
    ISNULL(P.VLR_AGUARDANDO, 0)   AS VLR_AGUARDANDO,
    ISNULL(P.QTD_NAO_AVERBADO, 0) AS QTD_NAO_AVERBADO,
    ISNULL(P.VLR_NAO_AVERBADO, 0) AS VLR_NAO_AVERBADO,
    ISNULL(T.QTD_TENTATIVAS, 0)   AS QTD_TENTATIVAS,
    ISNULL(T.QTD_CONVERTIDAS, 0)  AS QTD_CONVERTIDAS
FROM LOJAS L
LEFT JOIN PROD P ON P.CHAVE_LOJA = L.CHAVE_LOJA
LEFT JOIN TENT T ON T.CHAVE_LOJA = L.CHAVE_LOJA
/*SOMENTE_COM_MOVIMENTO*/
ORDER BY ISNULL(P.VLR_AVERBADO, 0) DESC, ISNULL(T.QTD_TENTATIVAS, 0) DESC;
