SELECT
    T.PRODUTO,
    CAST(T.DATA_ETAPA AS DATE)              AS DATA_ETAPA,
    SUM(T.QTD_TENTATIVAS_TOTAL)             AS QTD_TENTATIVAS_TOTAL,
    SUM(T.QTD_CLIENTES)                     AS QTD_CLIENTES,
    SUM(T.QTD_CONVERTIDAS)                  AS QTD_CONVERTIDOS,
    SUM(T.QTD_ABANDONADAS)                  AS QTD_ABANDONADAS,
    SUM(T.QTD_ERRO_INELEGIBILIDADE)         AS QTD_ERRO_INELEGIBILIDADE,
    SUM(ISNULL(T.QTD_OUTROS_ERROS, 0))      AS QTD_OUTROS_ERROS
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
WHERE T.CHAVE_LOJA = ?
  AND T.DATA_ETAPA >= CAST(? AS DATE) AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
GROUP BY T.PRODUTO, CAST(T.DATA_ETAPA AS DATE)
ORDER BY CAST(T.DATA_ETAPA AS DATE) DESC, T.PRODUTO;
