SELECT TOP (5000)
    CAST(P.DATA_TRX AS DATE)        AS DIA,
    P.INDICADOR,
    P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
    P.CONTRATO,
    P.NSU_TRX,
    P.CPF_CLIENTE,
    P.VLR_CONTRATO
FROM DEF..TB_CONSIG_AVERBADO_EXP P
WHERE P.CHAVE_LOJA = ?
  AND P.DATA_TRX >= CAST(? AS DATE)
  AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
  /*SITUACAO*/
ORDER BY P.DATA_TRX DESC, P.VLR_CONTRATO DESC;
