WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
CALENDARIO AS (
    SELECT
        CAST(D.DT_REFERENCIA AS DATE)                                         AS DATA,
        YEAR(D.DT_REFERENCIA) * 100 + MONTH(D.DT_REFERENCIA)                  AS MES,
        CASE WHEN D.QT_DIAS_UTEIS_MES = 0 THEN 1 ELSE D.QT_DIAS_UTEIS_MES END AS DU
    FROM MESU..TB_DIA_UTIL D
    WHERE D.DT_REFERENCIA >= CAST(? AS DATE)
      AND D.DT_REFERENCIA < DATEADD(DAY, 1, CAST(? AS DATE))
)
SELECT
    C.MES,
    C.DU,
    SUM(T.QTD_TENTATIVAS_TOTAL) AS QTD_TENTATIVAS,
    SUM(T.QTD_CONVERTIDAS)      AS QTD_CONVERTIDAS
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
INNER JOIN LOJAS L ON L.CHAVE_LOJA = T.CHAVE_LOJA
INNER JOIN CALENDARIO C ON C.DATA = CAST(T.DATA_ETAPA AS DATE)
WHERE T.DATA_ETAPA >= CAST(? AS DATE)
  AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
GROUP BY C.MES, C.DU
ORDER BY C.MES, C.DU;
