SELECT
    CAST(D.DT_REFERENCIA AS DATE)                                         AS DATA,
    YEAR(D.DT_REFERENCIA) * 100 + MONTH(D.DT_REFERENCIA)                  AS MES,
    CASE WHEN D.QT_DIAS_UTEIS_MES = 0 THEN 1 ELSE D.QT_DIAS_UTEIS_MES END AS DU
FROM MESU..TB_DIA_UTIL D
WHERE D.DT_REFERENCIA >= CAST(? AS DATE)
  AND D.DT_REFERENCIA < DATEADD(DAY, 1, CAST(? AS DATE))
ORDER BY D.DT_REFERENCIA;
