-- Primeiro DU em que cada loja produziu no mes; o Python acumula para
-- montar a serie de "lojas produtivas ate o DU N".
WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
CALENDARIO AS (
    SELECT
        CAST(D.DT_REFERENCIA AS DATE)                                         AS DATA,
        YEAR(D.DT_REFERENCIA) * 100 + MONTH(D.DT_REFERENCIA)                  AS MES,
        CASE WHEN D.QT_DIAS_UTEIS_MES = 0 THEN 1 ELSE D.QT_DIAS_UTEIS_MES END AS DU
    FROM MESU..TB_DIA_UTIL D
    WHERE D.DT_REFERENCIA >= CAST(? AS DATE)
      AND D.DT_REFERENCIA < DATEADD(DAY, 1, CAST(? AS DATE))
),
PRIMEIRO AS (
    SELECT C.MES, P.CHAVE_LOJA, MIN(C.DU) AS DU
    FROM DEF..TB_CONSIG_AVERBADO_EXP P
    INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
    INNER JOIN CALENDARIO C ON C.DATA = CAST(P.DATA_TRX AS DATE)
    WHERE P.DATA_TRX >= CAST(? AS DATE)
      AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
      AND P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO'
      /*PRODUTO*/
    GROUP BY C.MES, P.CHAVE_LOJA
)
SELECT MES, DU, COUNT(*) AS QTD_LOJAS_NOVAS
FROM PRIMEIRO
GROUP BY MES, DU
ORDER BY MES, DU;
