-- Producao AVERBADA por loja e mes, recortada pelo DU N (?): acumulado ate N,
-- valor no DU N e ultimo DU com producao. Universo = lojas que produziram
-- em algum dos meses comparados (nao corta por lojas ativas).
WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        LTRIM(RTRIM(A.NOME_LOJA)) AS NOME_LOJA,
        H.CHAVE_GERENCIA_AREA, H.DESC_GERENCIA_AREA,
        H.CHAVE_COORDENACAO,   H.DESC_COORDENACAO,
        H.CHAVE_SUPERVISAO,    H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
CALENDARIO AS (
    SELECT
        CAST(D.DT_REFERENCIA AS DATE)                                         AS DATA,
        YEAR(D.DT_REFERENCIA) * 100 + MONTH(D.DT_REFERENCIA)                  AS MES,
        CASE WHEN D.QT_DIAS_UTEIS_MES = 0 THEN 1 ELSE D.QT_DIAS_UTEIS_MES END AS DU
    FROM MESU..TB_DIA_UTIL D
    WHERE D.DT_REFERENCIA >= CAST(? AS DATE)
      AND D.DT_REFERENCIA < DATEADD(DAY, 1, CAST(? AS DATE))
)
SELECT
    L.CHAVE_LOJA,
    MAX(L.NOME_LOJA)           AS NOME_LOJA,
    MAX(L.CHAVE_GERENCIA_AREA) AS CHAVE_GERENCIA,
    MAX(L.DESC_GERENCIA_AREA)  AS DESC_GERENCIA,
    MAX(L.CHAVE_COORDENACAO)   AS CHAVE_COORDENACAO,
    MAX(L.DESC_COORDENACAO)    AS DESC_COORDENACAO,
    MAX(L.CHAVE_SUPERVISAO)    AS CHAVE_SUPERVISAO,
    MAX(L.DESC_SUPERVISAO)     AS DESC_SUPERVISAO,
    C.MES,
    ISNULL(SUM(CASE WHEN C.DU <= ? THEN P.VLR_CONTRATO END), 0) AS VLR_ACUM,
    SUM(CASE WHEN C.DU <= ? THEN 1 ELSE 0 END)                  AS QTD_ACUM,
    ISNULL(SUM(CASE WHEN C.DU =  ? THEN P.VLR_CONTRATO END), 0) AS VLR_DU,
    SUM(CASE WHEN C.DU =  ? THEN 1 ELSE 0 END)                  AS QTD_DU,
    ISNULL(MAX(CASE WHEN C.DU <= ? THEN C.DU END), 0)           AS ULTIMO_DU
FROM DEF..TB_CONSIG_AVERBADO_EXP P
INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
INNER JOIN CALENDARIO C ON C.DATA = CAST(P.DATA_TRX AS DATE)
WHERE P.DATA_TRX >= CAST(? AS DATE)
  AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
  AND P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO'
  /*PRODUTO*/
GROUP BY L.CHAVE_LOJA, C.MES;
