WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        H.CHAVE_GERENCIA_AREA, H.DESC_GERENCIA_AREA,
        H.CHAVE_COORDENACAO,   H.DESC_COORDENACAO,
        H.CHAVE_SUPERVISAO,    H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
PRODUCAO AS (
    SELECT
        /*NIVEL_CHAVE*/ AS CHAVE,
        L.CHAVE_LOJA,
        CASE P.INDICADOR
             WHEN N'CRÉDITO CONSIGNADO INSS'    THEN 'INSS'
             WHEN N'CRÉDITO CONSIGNADO PRIVADO' THEN 'PRIVADO'
             WHEN N'CRÉDITO CONSIGNADO PUBLICO' THEN 'PUBLICO'
        END AS PRODUTO,
        P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
        P.VLR_CONTRATO
    FROM DEF..TB_CONSIG_AVERBADO_EXP P
    INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
    WHERE P.DATA_TRX >= CAST(? AS DATE)
      AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
)
SELECT
    CHAVE,
    PRODUTO,
    SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN 1 ELSE 0 END)                         AS QTD_OPERACOES,
    COUNT(DISTINCT CASE WHEN SITUACAO = 'AVERBADO' THEN CHAVE_LOJA END)           AS QTD_LOJAS,
    ISNULL(SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN VLR_CONTRATO END), 0)             AS VLR_PRODUCAO,
    ISNULL(SUM(CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN VLR_CONTRATO END), 0) AS VLR_AGUARDANDO
FROM PRODUCAO
WHERE PRODUTO IS NOT NULL
GROUP BY CHAVE, PRODUTO;
