WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        H.CHAVE_GERENCIA_AREA, H.DESC_GERENCIA_AREA,
        H.CHAVE_COORDENACAO,   H.DESC_COORDENACAO,
        H.CHAVE_SUPERVISAO,    H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    /*NIVEL_CHAVE*/             AS CHAVE,
    T.PRODUTO                   AS PRODUTO,
    SUM(T.QTD_TENTATIVAS_TOTAL) AS QTD_TENTATIVAS,
    SUM(T.QTD_CONVERTIDAS)      AS QTD_CONVERTIDAS
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
INNER JOIN LOJAS L ON L.CHAVE_LOJA = T.CHAVE_LOJA
WHERE T.DATA_ETAPA >= CAST(? AS DATE) AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
GROUP BY /*NIVEL_CHAVE*/, T.PRODUTO;
