WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        H.CHAVE_GERENCIA_AREA, H.DESC_GERENCIA_AREA,
        H.CHAVE_COORDENACAO,   H.DESC_COORDENACAO,
        H.CHAVE_SUPERVISAO,    H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
      AND A.CHAVE_LOJA IN (
            SELECT DISTINCT CHAVE_LOJA
            FROM DATAWAREHOUSE..TB_INDICADORES_BE
            WHERE PERIODO BETWEEN ? AND ?
              AND QTD_ATIVOS > 0
      )
)
SELECT
    /*NIVEL_CHAVE*/              AS CHAVE,
    /*NIVEL_DESC*/               AS DESCRICAO,
    COUNT(DISTINCT L.CHAVE_LOJA) AS QTD_LOJAS,
    COUNT(DISTINCT P.CHAVE_LOJA) AS QTD_LOJAS_PRODUCAO
    /*COLS_PAIS*/
FROM LOJAS L
LEFT JOIN DEF..TB_CONSIG_AVERBADO_EXP P
    ON P.CHAVE_LOJA = L.CHAVE_LOJA
   AND P.ANO_MES BETWEEN ? AND ?
   AND P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO'
GROUP BY /*NIVEL_CHAVE*/, /*NIVEL_DESC*/
ORDER BY /*NIVEL_DESC*/;
