WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        LTRIM(RTRIM(A.NOME_LOJA)) AS NOME_LOJA,
        H.DESC_GERENCIA_AREA,
        H.DESC_COORDENACAO,
        H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    L.DESC_GERENCIA_AREA,
    L.DESC_COORDENACAO,
    L.DESC_SUPERVISAO,
    L.CHAVE_LOJA,
    L.NOME_LOJA,
    CAST(P.DATA_TRX AS DATE)        AS DIA,
    P.INDICADOR,
    P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
    P.CONTRATO,
    P.NSU_TRX,
    P.CPF_CLIENTE,
    P.VLR_CONTRATO
FROM DEF..TB_CONSIG_AVERBADO_EXP P
INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
WHERE P.DATA_TRX >= CAST(? AS DATE)
  AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
  /*SITUACAO*/
ORDER BY P.DATA_TRX DESC, P.VLR_CONTRATO DESC;
