WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        LTRIM(RTRIM(A.NOME_LOJA)) AS NOME_LOJA,
        H.DESC_GERENCIA_AREA,
        H.DESC_COORDENACAO,
        H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    L.DESC_GERENCIA_AREA,
    L.DESC_COORDENACAO,
    L.DESC_SUPERVISAO,
    L.CHAVE_LOJA,
    L.NOME_LOJA,
    T.PRODUTO,
    CAST(T.DATA_ETAPA AS DATE)  AS DATA_ETAPA,
    ISNULL(SUM(T.QTD_CLIENTES), 0) AS QTD_CLIENTES,
    SUM(T.QTD_CONVERTIDAS)      AS QTD_CONVERTIDOS,
    SUM(T.QTD_ABANDONADAS)      AS QTD_ABANDONADAS,
    SUM(T.QTD_ERRO_INELEGIBILIDADE) AS QTD_ERRO_INELEGIBILIDADE,
    SUM(ISNULL(T.QTD_OUTROS_ERROS, 0)) AS QTD_OUTROS_ERROS
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
INNER JOIN LOJAS L ON L.CHAVE_LOJA = T.CHAVE_LOJA
WHERE T.DATA_ETAPA >= CAST(? AS DATE)
  AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
GROUP BY
    L.DESC_GERENCIA_AREA,
    L.DESC_COORDENACAO,
    L.DESC_SUPERVISAO,
    L.CHAVE_LOJA,
    L.NOME_LOJA,
    T.PRODUTO,
    CAST(T.DATA_ETAPA AS DATE)
ORDER BY CAST(T.DATA_ETAPA AS DATE) DESC, L.NOME_LOJA, T.PRODUTO;
