SELECT DISTINCT
    CHAVE_GERENCIA_AREA,
    DESC_GERENCIA_AREA,
    CHAVE_COORDENACAO,
    DESC_COORDENACAO,
    CHAVE_SUPERVISAO,
    DESC_SUPERVISAO
FROM MESU..CONS_DISTRIBUICAO_ENTIDADES
WHERE CHAVE_GERENCIA_AREA IS NOT NULL
ORDER BY DESC_GERENCIA_AREA, DESC_COORDENACAO, DESC_SUPERVISAO;
