WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    ISNULL(SUM(T.QTD_TENTATIVAS_TOTAL), 0) AS QTD_TENTATIVAS,
    ISNULL(SUM(T.QTD_CONVERTIDAS), 0)      AS QTD_CONVERTIDAS,
    ISNULL(SUM(T.QTD_CLIENTES), 0)         AS QTD_CLIENTES
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
INNER JOIN LOJAS L ON L.CHAVE_LOJA = T.CHAVE_LOJA
WHERE T.DATA_ETAPA >= CAST(? AS DATE) AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/;
