WITH LOJAS AS (
    SELECT DISTINCT
        A.CHAVE_LOJA,
        H.CHAVE_GERENCIA_AREA, H.DESC_GERENCIA_AREA,
        H.CHAVE_COORDENACAO,   H.DESC_COORDENACAO,
        H.CHAVE_SUPERVISAO,    H.DESC_SUPERVISAO
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    /*NIVEL_CHAVE*/                  AS CHAVE,
    CAST(P.DATA_TRX AS DATE)         AS DIA,
    SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO' THEN 1 ELSE 0 END)                           AS QTD_AVERBADO,
    ISNULL(SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO' THEN P.VLR_CONTRATO END), 0)             AS VLR_AVERBADO,
    SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AGUARDANDO AVERBACAO' THEN 1 ELSE 0 END)               AS QTD_AGUARDANDO,
    ISNULL(SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'AGUARDANDO AVERBACAO' THEN P.VLR_CONTRATO END), 0) AS VLR_AGUARDANDO,
    SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'NAO AVERBADO' THEN 1 ELSE 0 END)                       AS QTD_NAO_AVERBADO,
    ISNULL(SUM(CASE WHEN P.SITUACAO_CONTRATO_CONSOLIDADO = 'NAO AVERBADO' THEN P.VLR_CONTRATO END), 0)         AS VLR_NAO_AVERBADO
FROM DEF..TB_CONSIG_AVERBADO_EXP P
INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
WHERE P.DATA_TRX >= CAST(? AS DATE)
  AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
GROUP BY /*NIVEL_CHAVE*/, CAST(P.DATA_TRX AS DATE);
