WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    CAST(T.DATA_ETAPA AS DATE)  AS DIA,
    SUM(T.QTD_TENTATIVAS_TOTAL) AS QTD_TENTATIVAS,
    SUM(T.QTD_CONVERTIDAS)      AS QTD_CONVERTIDAS
FROM TESTE..TENTATIVAS_CONSIGNADO_DIA T
INNER JOIN LOJAS L ON L.CHAVE_LOJA = T.CHAVE_LOJA
WHERE T.DATA_ETAPA >= CAST(? AS DATE) AND T.DATA_ETAPA < DATEADD(DAY, 1, CAST(? AS DATE))
  /*PRODUTO*/
GROUP BY CAST(T.DATA_ETAPA AS DATE);
