WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
)
SELECT
    P.ANO_MES                      AS DIA_INT,
    COUNT(*)                       AS QTD_OPERACOES,
    ISNULL(SUM(P.VLR_CONTRATO), 0) AS VLR_PRODUCAO
FROM DEF..TB_CONSIG_AVERBADO_EXP P
INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
WHERE P.ANO_MES BETWEEN ? AND ?
  AND P.SITUACAO_CONTRATO_CONSOLIDADO = 'AVERBADO'
  /*PRODUTO*/
GROUP BY P.ANO_MES
ORDER BY P.ANO_MES;
