WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
PRODUCAO AS (
    SELECT
        CAST(P.DATA_TRX AS DATE) AS DIA,
        P.CHAVE_LOJA,
        CASE P.INDICADOR
             WHEN N'CRÉDITO CONSIGNADO INSS'    THEN 'INSS'
             WHEN N'CRÉDITO CONSIGNADO PRIVADO' THEN 'PRIVADO'
             WHEN N'CRÉDITO CONSIGNADO PUBLICO' THEN 'PUBLICO'
        END AS PRODUTO,
        P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
        P.VLR_CONTRATO
    FROM DEF..TB_CONSIG_AVERBADO_EXP P
    INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
    WHERE P.DATA_TRX >= CAST(? AS DATE)
      AND P.DATA_TRX < DATEADD(DAY, 1, CAST(? AS DATE))
),
POR_PRODUTO AS (
    SELECT
        DIA,
        PRODUTO,
        SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN 1 ELSE 0 END)                             AS QTD_AVERBADO,
        COUNT(DISTINCT CASE WHEN SITUACAO = 'AVERBADO' THEN CHAVE_LOJA END)               AS QTD_LOJAS,
        ISNULL(SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN VLR_CONTRATO END), 0)             AS VLR_AVERBADO,
        SUM(CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN 1 ELSE 0 END)                 AS QTD_AGUARDANDO,
        ISNULL(SUM(CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN VLR_CONTRATO END), 0) AS VLR_AGUARDANDO,
        SUM(CASE WHEN SITUACAO = 'NAO AVERBADO' THEN 1 ELSE 0 END)                         AS QTD_NAO_AVERBADO,
        ISNULL(SUM(CASE WHEN SITUACAO = 'NAO AVERBADO' THEN VLR_CONTRATO END), 0)         AS VLR_NAO_AVERBADO
    FROM PRODUCAO
    WHERE PRODUTO IS NOT NULL
    GROUP BY DIA, PRODUTO
),
POR_DIA AS (
    SELECT
        DIA,
        COUNT(DISTINCT CASE WHEN SITUACAO = 'AVERBADO' THEN CHAVE_LOJA END)               AS LOJAS_AVERBADO,
        COUNT(DISTINCT CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN CHAVE_LOJA END)   AS LOJAS_AGUARDANDO,
        COUNT(DISTINCT CASE WHEN SITUACAO = 'NAO AVERBADO' THEN CHAVE_LOJA END)           AS LOJAS_NAO_AVERBADO
    FROM PRODUCAO
    WHERE PRODUTO IS NOT NULL
    GROUP BY DIA
)
SELECT
    P.DIA,
    P.PRODUTO,
    P.QTD_AVERBADO,
    P.QTD_LOJAS,
    P.VLR_AVERBADO,
    P.QTD_AGUARDANDO,
    P.VLR_AGUARDANDO,
    P.QTD_NAO_AVERBADO,
    P.VLR_NAO_AVERBADO,
    D.LOJAS_AVERBADO,
    D.LOJAS_AGUARDANDO,
    D.LOJAS_NAO_AVERBADO
FROM POR_PRODUTO P
INNER JOIN POR_DIA D ON D.DIA = P.DIA
ORDER BY P.DIA DESC;
