WITH LOJAS AS (
    SELECT DISTINCT A.CHAVE_LOJA
    FROM DATALAKE..DL_BRADESCO_EXPRESSO A
    INNER JOIN MESU..CONS_DISTRIBUICAO_ENTIDADES H
        ON TRY_CAST(H.COD_AG AS BIGINT) = A.COD_AG_LOJA
    WHERE A.TIPO_POSTO IN ('Tradicional', 'Ilha')
      /*FILTROS*/
),
PRODUCAO AS (
    SELECT
        P.ANO_MES AS DIA_INT,
        CASE P.INDICADOR
             WHEN N'CRÉDITO CONSIGNADO INSS'    THEN 'INSS'
             WHEN N'CRÉDITO CONSIGNADO PRIVADO' THEN 'PRIVADO'
             WHEN N'CRÉDITO CONSIGNADO PUBLICO' THEN 'PUBLICO'
        END AS PRODUTO,
        P.SITUACAO_CONTRATO_CONSOLIDADO AS SITUACAO,
        P.VLR_CONTRATO
    FROM DEF..TB_CONSIG_AVERBADO_EXP P
    INNER JOIN LOJAS L ON L.CHAVE_LOJA = P.CHAVE_LOJA
    WHERE P.ANO_MES BETWEEN ? AND ?
)
SELECT
    DIA_INT,
    PRODUTO,
    SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN 1 ELSE 0 END)                             AS QTD_AVERBADO,
    ISNULL(SUM(CASE WHEN SITUACAO = 'AVERBADO' THEN VLR_CONTRATO END), 0)             AS VLR_AVERBADO,
    SUM(CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN 1 ELSE 0 END)                 AS QTD_AGUARDANDO,
    ISNULL(SUM(CASE WHEN SITUACAO = 'AGUARDANDO AVERBACAO' THEN VLR_CONTRATO END), 0) AS VLR_AGUARDANDO,
    SUM(CASE WHEN SITUACAO = 'NAO AVERBADO' THEN 1 ELSE 0 END)                         AS QTD_NAO_AVERBADO,
    ISNULL(SUM(CASE WHEN SITUACAO = 'NAO AVERBADO' THEN VLR_CONTRATO END), 0)         AS VLR_NAO_AVERBADO
FROM PRODUCAO
WHERE PRODUTO IS NOT NULL
GROUP BY DIA_INT, PRODUTO
ORDER BY DIA_INT DESC;
